using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SAI_NETSUITE.Models.Transaccion;
using DevExpress.XtraGrid;
using DevExpress.XtraEditors;

namespace SAI_NETSUITE.Views.Logistica.MesaControl
{
    public partial class Planeador : UserControl
    {
        public Planeador()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource



            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
           // sqlDataSource1.Fill();
        }

        private void btnActualizar_Click(object sender, EventArgs e)
        {
            if (backgroundWorker1.IsBusy)
                MessageBox.Show("Espera todavia no termina");
            else
            {
                btnActualizar.ImageOptions.Image = SAI_NETSUITE.Properties.Resources.gear;
                backgroundWorker1.RunWorkerAsync();
               // sqlDataSource1.Fill();


               
            }
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
             Controllers.Logistica.MesaControl.PlaneadorController pc = new Controllers.Logistica.MesaControl.PlaneadorController();

             List<PlaneadorModel> lista = pc.GetPlaneadors();

             e.Result = lista;

          

        }

        private void backgroundWorker1_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {
              List<PlaneadorModel> lista =(List<PlaneadorModel>) e.Result;
              pivotGridControl1.DataSource = lista;
           
            // sqlDataSource1.Fill();
            btnActualizar.ImageOptions.Image = null;
            labelControl1.Text = DateTime.Now.ToShortTimeString();
        }

        private void sqlDataSource1_ValidateCustomSqlQuery(object sender, DevExpress.DataAccess.ValidateCustomSqlQueryEventArgs e)
        {
           e.Valid = true;
        }

        private void btnCajasPendientes_Click(object sender, EventArgs e)
        {
            Controllers.Logistica.MesaControl.CajasPendientes cp = new Controllers.Logistica.MesaControl.CajasPendientes();
            cp.Show();
        }
    }
}
