//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int internalid { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string numProspect { get; set; }
        public string idNet { get; set; }
        public string companyId { get; set; }
        public string company { get; set; }
        public string tradeName { get; set; }
        public string RFC { get; set; }
        public string account { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> creditLimit { get; set; }
        public string bankReference { get; set; }
        public Nullable<bool> newPagare { get; set; }
        public Nullable<decimal> ammountPagare { get; set; }
        public Nullable<bool> newCustomerBonus { get; set; }
        public Nullable<decimal> limitOrders { get; set; }
        public Nullable<bool> newCreditRequest { get; set; }
        public Nullable<bool> modifyExpiration { get; set; }
        public Nullable<int> shippingWayId { get; set; }
        public Nullable<int> giroId { get; set; }
        public Nullable<int> MethodPayment { get; set; }
        public Nullable<int> TypeCustomer { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> ExtendExpiration { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<int> RouteSale { get; set; }
        public Nullable<int> Route { get; set; }
        public Nullable<int> CrmInfluence { get; set; }
        public Nullable<int> CommercialTerms { get; set; }
        public Nullable<int> BlockDelinquents { get; set; }
        public Nullable<int> Territory { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CountedCustomer { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> PriceList { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> customerGroup { get; set; }
        public Nullable<int> salesRep { get; set; }
        public Nullable<int> salesSupport { get; set; }
        public Nullable<int> serviceAgent { get; set; }
        public Nullable<int> accountingAssistant { get; set; }
        public Nullable<System.DateTime> lastModifiedDate { get; set; }
    
        public virtual FormaEnvio FormaEnvio { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual ListaPrecios ListaPrecios { get; set; }
    }
}
