//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasReporteXEmbarcar
    {
        public int idReporteXEmbarcar { get; set; }
        public string Estado { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> Dias { get; set; }
    }
}
