//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embarques
    {
        public Nullable<int> entity_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }
        public string estatus { get; set; }
        public int idEmbarque { get; set; }
        public Nullable<int> idPaqueteria { get; set; }
    
        public virtual EmbarquesD EmbarquesD { get; set; }
    }
}
