//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmbarquesD
    {
        public int idEmbarque { get; set; }
        public string factura { get; set; }
        public string entity_id { get; set; }
        public string formaEnvio { get; set; }
        public string paqueteria { get; set; }
        public string estado { get; set; }
        public string persona { get; set; }
        public string fechaHora { get; set; }
        public string comentarios { get; set; }
    
        public virtual Embarques Embarques { get; set; }
    }
}
