//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public string ADDRESS_ONE { get; set; }
        public string ADDRESS_THREE { get; set; }
        public string ADDRESS_TWO { get; set; }
        public Nullable<int> AGENTE_ID { get; set; }
        public string APLICA_PARA_BONO { get; set; }
        public Nullable<double> APOYOS_A_MERCADOTECNIA { get; set; }
        public string APOYO_VENTAS { get; set; }
        public string AUXILIAR_DE_COBRANZA { get; set; }
        public Nullable<int> BANCO_DESTINO_ID { get; set; }
        public Nullable<int> BANCO_ORIGEN_ID { get; set; }
        public Nullable<int> BLOQUEAR_MOROSOS_ID { get; set; }
        public Nullable<int> CATEGORA_DE_CLIENTE_ID { get; set; }
        public string CHECAR_CREDITO { get; set; }
        public string CITY { get; set; }
        public string CLABE { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> CLIENTE_CONTADO_ID { get; set; }
        public Nullable<double> COMPROMISO_DE_COMPRA { get; set; }
        public Nullable<int> CONDICIONES_COMERCIALES_ID { get; set; }
        public Nullable<int> CONDICIONES_DE_VENCIMIENTO_ID { get; set; }
        public Nullable<int> CONDICION_ID { get; set; }
        public Nullable<int> CONSERVA_BO_ID { get; set; }
        public string CORREO_ELECTRNICO_AGENTE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREDITO_CON_CONDICIONES { get; set; }
        public string CREDITO_CON_DIAS { get; set; }
        public string CREDITO_CON_LIMITE { get; set; }
        public string CREDITO_ESPECIAL { get; set; }
        public Nullable<int> CRM_INFLUENCIA_ID { get; set; }
        public string CRM_MOV_VENTA { get; set; }
        public string CURP { get; set; }
        public Nullable<System.DateTime> DATE_LAST_MODIFIED { get; set; }
        public string DEF_MONEDA_CREDITO_MONEDA { get; set; }
        public Nullable<int> DEPARTAMENTO_ID { get; set; }
        public Nullable<double> DESCUENTOS_POR_CONVENIOS { get; set; }
        public Nullable<double> DESCUENTOS_POR_TEMPORADA { get; set; }
        public Nullable<double> DESCUENTO_FINANCIERO { get; set; }
        public string DESCUENTO_RECARGOS { get; set; }
        public Nullable<int> DIA_INHABIL_ID { get; set; }
        public Nullable<int> DIC { get; set; }
        public string EMAIL { get; set; }
        public string ENTITY_EXTID { get; set; }
        public int ENTITY_ID { get; set; }
        public string ENTITY_TYPE { get; set; }
        public string ES_AGENTE { get; set; }
        public Nullable<int> FAMILIA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_DE_CUMPLEAOS { get; set; }
        public string FIRST_NAME { get; set; }
        public Nullable<int> FORMAS_DE_PAGO_ID { get; set; }
        public Nullable<int> FORMA_DE_ENVIO_ID { get; set; }
        public Nullable<int> FORMA_DE_PAGO_ID { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<int> GIRO_ID { get; set; }
        public Nullable<double> GLOBAL_SUBSCRIPTION_STATUS { get; set; }
        public Nullable<int> GRUPO_ID { get; set; }
        public string ICO { get; set; }
        public string ID_NET { get; set; }
        public Nullable<int> INCOTERM_ID { get; set; }
        public string INDAR_BONO_CLIENTE_NUEVO { get; set; }
        public Nullable<int> INDAR_RUTA_VENTA_ID { get; set; }
        public string IS_INACTIVE { get; set; }
        public string IS_ONLINE_BILL_PAY { get; set; }
        public string IS_UNAVAILABLE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> LAST_SALES_ACTIVITY { get; set; }
        public Nullable<double> LIMITE_PEDIDOS { get; set; }
        public string LOGIN_ACCESS { get; set; }
        public string LSA_LINK { get; set; }
        public string LSA_LINK_NAME { get; set; }
        public Nullable<int> METODO_DE_PAGOSAT_ID { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string MNIMO_DE_PEDIDO { get; set; }
        public string MODIFICAR_VENCIMIENTO { get; set; }
        public Nullable<double> MONTO_PAGARE { get; set; }
        public Nullable<int> MTODO_DE_PAGO_ID { get; set; }
        public Nullable<int> MTODO_DE_PAGO_SATC_ID { get; set; }
        public string NACIONALIDAD_EXTRANJERO { get; set; }
        public string NAME { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string NOMBRE_EXTRANJERO_DIOT { get; set; }
        public string NOTES { get; set; }
        public string NO_PROSPECTO { get; set; }
        public string NUMERO_ID_FISCAL_EXTRANJERO { get; set; }
        public string NUMREGIDTRIB { get; set; }
        public string NUM_CUENTA_PAGO { get; set; }
        public string NUM_DE_PROVEEDOR { get; set; }
        public string NUM__CLIENTE_INDAR { get; set; }
        public Nullable<double> N__DESCUENTO_ADICIONAL { get; set; }
        public Nullable<double> N__DESCUENTO_FINANCIERO { get; set; }
        public Nullable<double> N__DESCUENTO_PRONTO_PAGO { get; set; }
        public string ORIGINATOR_ID { get; set; }
        public string PAGARE_NUEVO { get; set; }
        public Nullable<int> PAQUETERIA_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> PAS_DE_RESIDENCIA_EXTRANJER_ID { get; set; }
        public string PEDIDOS_PARCIALES { get; set; }
        public string PHONE { get; set; }
        public string POLTICA_DE_DEPURACIN_BO { get; set; }
        public Nullable<int> RECORRER_VENCIMIENTO_ID { get; set; }
        public string REFERENCIA_BANCARIA { get; set; }
        public Nullable<int> REGIMEN_FISCAL_ID { get; set; }
        public string REPRESENTANTE_VTAS { get; set; }
        public string RFC { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
        public string R_F_C_ { get; set; }
        public string SALUTATION { get; set; }
        public string SOLICITUD_CREDITO_NUEVO { get; set; }
        public string STATE { get; set; }
        public Nullable<double> SUBSIDIARY { get; set; }
        public string SUPPORT_EMAIL_MVZ { get; set; }
        public string TAX_CONTACT_FIRST_NAME { get; set; }
        public string TAX_CONTACT_ID { get; set; }
        public string TAX_CONTACT_LAST_NAME { get; set; }
        public string TAX_CONTACT_MIDDLE_NAME { get; set; }
        public string TAX_IDENTIFICATION_NUMBER { get; set; }
        public Nullable<int> TIPO_DE_ADDENDA_ID { get; set; }
        public Nullable<int> TIPO_DE_ENTIDAD_ID { get; set; }
        public Nullable<int> TIPO_DE_OPERACIN_DIOT_ID { get; set; }
        public Nullable<int> TIPO_DE_PROVEEDOR_DIOT_ID { get; set; }
        public Nullable<int> TRMINOS_DE_PAGO_1_ID { get; set; }
        public Nullable<int> TRMINOS_DE_PAGO_2_ID { get; set; }
        public Nullable<int> TRMINOS_DE_PAGO_3_ID { get; set; }
        public string UNSUBSCRIBED { get; set; }
        public Nullable<int> USO_DEL_CFDI_ID { get; set; }
        public Nullable<int> VAT_REGISTRATION_NO { get; set; }
        public string ZIPCODE { get; set; }
        public string ZONA_ID { get; set; }
        public Nullable<int> ESTATUS_CLIENTE_INDAR_ID { get; set; }
        public string NO_BORRAR { get; set; }
    }
}
