//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorTimbradoPago
    {
        public int idErrorTimbradoPago { get; set; }
        public Nullable<int> internalId { get; set; }
        public string tranid { get; set; }
        public string error { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
