//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estilo()
        {
            this.PedidoRenglon = new HashSet<PedidoRenglon>();
        }
    
        public int IdEstilo { get; set; }
        public int IdLinea { get; set; }
        public string Nombre { get; set; }
        public string IdCajaUnitario { get; set; }
        public System.DateTime FechaActualizado { get; set; }
        public int IdUsuarioActualiza { get; set; }
        public string Descripcion { get; set; }
        public string Clave { get; set; }
        public Nullable<byte> IdFabrica { get; set; }
        public Nullable<byte> IdClasificacion { get; set; }
        public Nullable<int> IdSubFamilia { get; set; }
        public Nullable<bool> TieneCaducidad { get; set; }
        public string Fabricante { get; set; }
        public string Unidad { get; set; }
        public Nullable<bool> Tipo_Caducidad { get; set; }
        public Nullable<int> DiasVigencia { get; set; }
        public Nullable<int> DiasMinimoRecibo { get; set; }
        public Nullable<int> DiasMinimoRechazo { get; set; }
        public Nullable<int> MultiploCaja { get; set; }
        public string Categoria { get; set; }
        public string TipoClasificacion { get; set; }
        public Nullable<double> PorcentajeReabastoPrimario { get; set; }
        public Nullable<double> PorcentajeReabastoSecundario { get; set; }
        public string LeyendaSurtido { get; set; }
        public Nullable<bool> TieneCodigoBarras { get; set; }
        public Nullable<bool> SinCodigoBarras { get; set; }
        public double Monto { get; set; }
        public Nullable<int> ForzarLeyendaSurtido { get; set; }
        public string LeyendaRecibo { get; set; }
        public Nullable<bool> EtiquetaPieza { get; set; }
        public Nullable<int> MultiploRecibo { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> MultiploReabasto { get; set; }
        public Nullable<int> MultiploSurtidoPick { get; set; }
        public Nullable<int> MultiploSurtidoBulk { get; set; }
        public Nullable<bool> ValidacionCapturaRecibo { get; set; }
        public Nullable<bool> ValidacionCapturaAlmacenado { get; set; }
        public Nullable<bool> ValidacionCapturaTraspaso { get; set; }
        public Nullable<bool> ValidacionCapturaSurtido { get; set; }
        public Nullable<bool> ValidacionCapturaInventario { get; set; }
        public Nullable<bool> ValidacionCapturaEmpaque { get; set; }
        public Nullable<bool> ValidacionCapturaReabasto { get; set; }
        public Nullable<int> MultiploVenta { get; set; }
        public Nullable<bool> CaoticaPick { get; set; }
        public Nullable<double> DemandaDiaria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoRenglon> PedidoRenglon { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
