//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoFleteraD
    {
        public int idGastoFleteraD { get; set; }
        public int idGastoFletera { get; set; }
        public Nullable<int> idNumGuia { get; set; }
        public string NumGuia { get; set; }
        public Nullable<decimal> importeGuia { get; set; }
        public Nullable<int> bultos { get; set; }
        public Nullable<int> cajas { get; set; }
        public Nullable<int> atados { get; set; }
        public Nullable<int> tarimas { get; set; }
        public string facturas { get; set; }
        public string metodo { get; set; }
        public string comentario { get; set; }
    
        public virtual GastoFletera GastoFletera { get; set; }
    }
}
