//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoFletera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastoFletera()
        {
            this.GastoFleteraD = new HashSet<GastoFleteraD>();
        }
    
        public int idGastoFletera { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idVendor { get; set; }
        public string Vendor { get; set; }
        public string numFactura { get; set; }
        public Nullable<decimal> importeFactura { get; set; }
        public Nullable<bool> checkRetencion { get; set; }
        public string uuid { get; set; }
        public string usuario { get; set; }
        public string comentario { get; set; }
        public Nullable<bool> autorizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoFleteraD> GastoFleteraD { get; set; }
    }
}
