//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IndarnegEntities : DbContext
    {
        public IndarnegEntities()
            : base("name=IndarnegEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NumeroGuiaNetsuite> NumeroGuiaNetsuite { get; set; }
        public virtual DbSet<sai_usuario> sai_usuario { get; set; }
        public virtual DbSet<Embarques> Embarques { get; set; }
        public virtual DbSet<NumeroGuiaNetsuiteD> NumeroGuiaNetsuiteD { get; set; }
        public virtual DbSet<OrdenCobro> OrdenCobro { get; set; }
        public virtual DbSet<OrdenCobroD> OrdenCobroD { get; set; }
        public virtual DbSet<SAD> SAD { get; set; }
        public virtual DbSet<EventosSurtidos> EventosSurtidos { get; set; }
        public virtual DbSet<NumeroGuiaNetsuiteC> NumeroGuiaNetsuiteC { get; set; }
        public virtual DbSet<EmbarquesD> EmbarquesD { get; set; }
    
        public virtual ObjectResult<spWMS_InsertaIR_Result> spWMS_InsertaIR(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spWMS_InsertaIR_Result>("spWMS_InsertaIR", iDParameter);
        }
    
        public virtual int spEmpaquePantallaNetsuite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEmpaquePantallaNetsuite");
        }
    
        public virtual ObjectResult<spReporteOrdenCobro_Result1> spReporteOrdenCobro(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReporteOrdenCobro_Result1>("spReporteOrdenCobro", iDParameter);
        }
    
        public virtual ObjectResult<string> spLiberaUsuarioWMS(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spLiberaUsuarioWMS", usuarioParameter);
        }
    }
}
