//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class IR
    {
        public IR()
        {
            this.IRD = new HashSet<IRD>();
        }
    
        public int id { get; set; }
        public string mov { get; set; }
        public string vendor { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> synWMS { get; set; }
    
        public virtual ICollection<IRD> IRD { get; set; }
    }
}
