//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRD
    {
        public int idIR { get; set; }
        public string itemid { get; set; }
        public Nullable<int> quantity { get; set; }
        public string sourceTran { get; set; }
        public Nullable<int> sourceNumber { get; set; }
        public int IRDid { get; set; }
    
        public virtual IR IR { get; set; }
    }
}
