//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemReceiptWMS
    {
        public string type { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> entity { get; set; }
        public Nullable<int> location { get; set; }
        public string item { get; set; }
        public Nullable<int> itemquantity { get; set; }
        public Nullable<int> id { get; set; }
        public int idReceipt { get; set; }
        public Nullable<bool> syncWMS { get; set; }
        public Nullable<int> tranid { get; set; }
        public string ordertype { get; set; }
    }
}
