//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.SaleOrdersDetails = new HashSet<SaleOrdersDetails>();
        }
    
        public string id { get; set; }
        public string type { get; set; }
        public string itemid { get; set; }
        public string displayname { get; set; }
        public Nullable<int> unitstype { get; set; }
        public string unitstypeText { get; set; }
        public Nullable<int> stockunit { get; set; }
        public string stockunitText { get; set; }
        public Nullable<int> purchaseunit { get; set; }
        public string purchaseunitText { get; set; }
        public Nullable<int> saleunit { get; set; }
        public string saleunitText { get; set; }
        public Nullable<int> baseunit { get; set; }
        public string baseunitText { get; set; }
        public string vendorname { get; set; }
        public string upccode { get; set; }
        public Nullable<int> department { get; set; }
        public string departmentText { get; set; }
        public Nullable<int> location { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string purchasedescription { get; set; }
        public Nullable<int> taxschedule { get; set; }
        public string taxscheduleText { get; set; }
        public Nullable<int> custitem_tipo_articulo { get; set; }
        public string custitem_tipo_articuloText { get; set; }
        public Nullable<int> custitem_fabricante_articulo { get; set; }
        public string custitem_fabricante_articuloText { get; set; }
        public Nullable<int> custitem_linea_articulo { get; set; }
        public string custitem_linea_articuloText { get; set; }
        public Nullable<int> custitem_categoria_articulo { get; set; }
        public string custitem_categoria_articuloText { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<bool> syncWMS { get; set; }
        public Nullable<int> custitem_tipo_clasif_art { get; set; }
        public string custitem_tipo_clasif_artText { get; set; }
        public Nullable<int> custitem_presentacion_individual { get; set; }
        public string custitem_codigo_sustituto { get; set; }
        public Nullable<decimal> custitem_costo_estandar { get; set; }
        public Nullable<int> custitem_familia_articulo { get; set; }
        public Nullable<int> custitem_grupo_articulo { get; set; }
        public string custitem_indar_excepcion { get; set; }
        public string custitem_indar_explicacion { get; set; }
        public string custitem_mensaje_emergente { get; set; }
        public Nullable<double> custitem_multiplos_ordenar { get; set; }
        public Nullable<int> custitem_nivel_indar { get; set; }
        public Nullable<int> custitem_rama_articulo { get; set; }
        public Nullable<int> custitem_ranking_imp { get; set; }
        public Nullable<int> custitem_ranking_pza { get; set; }
        public Nullable<bool> custitem_sustitutos { get; set; }
        public Nullable<int> custitem_temporada_articulo { get; set; }
        public Nullable<decimal> PrecioLista { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Precio4 { get; set; }
        public Nullable<decimal> Precio5 { get; set; }
        public Nullable<decimal> Precio6 { get; set; }
        public Nullable<decimal> Precio7 { get; set; }
        public Nullable<decimal> Precio8 { get; set; }
        public Nullable<decimal> Precio9 { get; set; }
        public Nullable<decimal> Precio10 { get; set; }
        public Nullable<double> maximumquantity { get; set; }
        public Nullable<double> minimunquantity { get; set; }
        public Nullable<bool> isInactive { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<decimal> maximoCompra { get; set; }
        public Nullable<decimal> multiploCompra { get; set; }
        public Nullable<decimal> multiploVenta { get; set; }
    
        public virtual ICollection<SaleOrdersDetails> SaleOrdersDetails { get; set; }
    }
}
