//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IWSEntities : DbContext
    {
        public IWSEntities()
            : base("name=IWSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customers> Customers { get; set; }
        public DbSet<Locations> Locations { get; set; }
        public DbSet<Address> Address { get; set; }
        public DbSet<FormaEnvio> FormaEnvio { get; set; }
        public DbSet<Ruta> Ruta { get; set; }
        public DbSet<Items> Items { get; set; }
        public DbSet<ListaPrecios> ListaPrecios { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
    }
}
