//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeroGuiaNetsuiteC
    {
        public int idNumeroGuia { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual NumeroGuiaNetsuite NumeroGuiaNetsuite { get; set; }
    }
}
