//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeroGuiaNetsuiteD
    {
        public int idNumeroGuia { get; set; }
        public Nullable<int> idFactura { get; set; }
        public string Factura { get; set; }
        public string RazonAutorizacion { get; set; }
        public Nullable<int> Autorizacion { get; set; }
    
        public virtual NumeroGuiaNetsuite NumeroGuiaNetsuite { get; set; }
    }
}
