//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEmbarque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenEmbarque()
        {
            this.PedidoRenglon = new HashSet<PedidoRenglon>();
        }
    
        public int IdOrdenEmbarque { get; set; }
        public string NumPedido { get; set; }
        public System.DateTime FechaEntregaReal { get; set; }
        public System.DateTime FechaEntregaOriginal { get; set; }
        public Nullable<System.DateTime> FechaEmbarque { get; set; }
        public Nullable<System.DateTime> FechaEmpaqueBase { get; set; }
        public Nullable<System.DateTime> FechaEmpaqueReal { get; set; }
        public byte IdEstatusOrdenEmbarque { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdConsignatario { get; set; }
        public Nullable<double> CantUnitarios { get; set; }
        public Nullable<System.DateTime> FechaInicioVA { get; set; }
        public Nullable<System.DateTime> FechaFinVA { get; set; }
        public Nullable<System.DateTime> FechaFinSurtido { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public System.DateTime FechaActualizado { get; set; }
        public int IdUsuarioActualiza { get; set; }
        public Nullable<byte> IdFabrica { get; set; }
        public Nullable<int> IdSubcliente { get; set; }
        public string Origen { get; set; }
        public string Mov { get; set; }
        public string FormaEnvio { get; set; }
        public string LugarEnvio { get; set; }
        public string Fletera { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public long IdPedido { get; set; }
        public string Consolidado { get; set; }
        public Nullable<bool> Eliminada { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string FacturaIndar { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<int> IdUsuarioLibera { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public Nullable<int> IdUsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoRenglon> PedidoRenglon { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
