//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCobroD
    {
        public int idOrdenCobro { get; set; }
        public string factura { get; set; }
        public string comentarios { get; set; }
        public int idOrdenCobroD { get; set; }
        public Nullable<int> facturaid { get; set; }
    
        public virtual OrdenCobro OrdenCobro { get; set; }
    }
}
