//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoRenglon
    {
        public int IdPedidoRenglon { get; set; }
        public Nullable<int> IdOrdenEmbarque { get; set; }
        public int NumPedido { get; set; }
        public int Renglon { get; set; }
        public Nullable<long> IdProducto { get; set; }
        public Nullable<double> CantUnitarios { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public byte IdEstatusOrdenEmbarque { get; set; }
        public Nullable<bool> EnBuro { get; set; }
        public Nullable<bool> Cancelada { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdConsignatario { get; set; }
        public string Tienda { get; set; }
        public string NumFactura { get; set; }
        public string NumSerie { get; set; }
        public Nullable<System.DateTime> FechaInicioVA { get; set; }
        public Nullable<System.DateTime> FechaFinVA { get; set; }
        public Nullable<System.DateTime> FechaFinSurtido { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<bool> ConCambio { get; set; }
        public System.DateTime FechaActualizado { get; set; }
        public int IdUsuarioActualiza { get; set; }
        public string Observaciones { get; set; }
        public Nullable<short> Orden { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public Nullable<double> CantSurtida { get; set; }
        public Nullable<int> IdEstilo { get; set; }
        public Nullable<int> CantCancelada { get; set; }
        public Nullable<System.DateTime> FechaCancelada { get; set; }
        public Nullable<double> CantConsolidada { get; set; }
        public Nullable<double> CantEmpacada { get; set; }
    
        public virtual OrdenEmbarque OrdenEmbarque { get; set; }
        public virtual Estilo Estilo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
