//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAD
    {
        public int sadID { get; set; }
        public Nullable<int> pedidoID { get; set; }
        public Nullable<int> pedido { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string excepcion { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> cxcMonto { get; set; }
        public string cxcAgente { get; set; }
        public Nullable<System.DateTime> cxcFecha { get; set; }
        public string cxcComentario { get; set; }
        public string validaAgente { get; set; }
        public Nullable<System.DateTime> validadFecha { get; set; }
    }
}
