//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class sai_usuario
    {
        public string usuario { get; set; }
        public string pass { get; set; }
        public string perfil { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public int id { get; set; }
        public Nullable<int> empleado { get; set; }
        public string foto { get; set; }
        public string puesto { get; set; }
        public string estatus { get; set; }
        public string sucursal { get; set; }
        public string area { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> ultimoInicioSesion { get; set; }
    }
}
