//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    
    public partial class spReporteOrdenCobro_Result1
    {
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }
        public string estatus { get; set; }
        public string NAME { get; set; }
        public string factura { get; set; }
        public string comentarios1 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public string NSO___TRMINOS_DE_PAGO_NAME { get; set; }
        public string status { get; set; }
        public int idOrdenCobro { get; set; }
    }
}
