//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminosDePago
    {
        public int nso___TRMINOS_DE_PAGO_ID { get; set; }
        public Nullable<int> TIPO_DE_ENTIDAD_ID { get; set; }
        public string NSO___TRMINOS_DE_PAGO_NAME { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<bool> isInactive { get; set; }
    }
}
