//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_RELACION_V3_3
    {
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string IS_INACTIVE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string TIPO_DE_RELACION_V3_3_EXTID { get; set; }
        public int TIPO_DE_RELACION_V3_3_ID { get; set; }
        public string TIPO_DE_RELACION_V3_3_NAME { get; set; }
        public string TIPO_DE_RELACION_V3_3_NUMBER { get; set; }
    }
}
