//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_NETSUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonasIndar
    {
        public Nullable<int> AGENTE_COBRADOR_ID { get; set; }
        public Nullable<int> APOYO_DE_VENTAS_ID { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<int> DEPARTAMENTO_ID { get; set; }
        public Nullable<int> Isnactive { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> NSO___ZONAS_CLIENTES_EXTID { get; set; }
        public int NSO___ZONAS_CLIENTES_ID { get; set; }
        public string NSO___ZONAS_CLIENTES_NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> REPRESENTANTE_VENTAS_ID { get; set; }
        public int ZONA_DE_VENTAS_ID { get; set; }
    }
}
